"""Add team member module models

Revision ID: 04d473b83321
Revises: 251ddcbbf24b
Create Date: 2025-10-08 10:42:48.871867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d473b83321'
down_revision = '251ddcbbf24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_order_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['finished_products.id'], ),
    sa.ForeignKeyConstraint(['team_order_id'], ['team_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finished_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('critical_stock_level', sa.Integer(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_street', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('address_postal_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('address_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('address_city')
        batch_op.drop_column('address_postal_code')
        batch_op.drop_column('address_street')

    with op.batch_alter_table('finished_products', schema=None) as batch_op:
        batch_op.drop_column('critical_stock_level')

    op.drop_table('team_order_products')
    op.drop_table('team_orders')
    # ### end Alembic commands ###
