"""Add unit_price to raw materials and packaging

Revision ID: 129c9f1baee7
Revises: 60da692b8fb2
Create Date: 2026-01-06 17:23:13.394706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129c9f1baee7'
down_revision = '60da692b8fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packaging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=False))

    with op.batch_alter_table('raw_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_materials', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    with op.batch_alter_table('packaging', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
