"""Manual remove unique constraint from product code

Revision ID: 19d13e37bae4
Revises: 
Create Date: 2025-09-15 12:27:12.038045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d13e37bae4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_products', schema=None) as batch_op:
        # Usuwamy regułę unikalności. Nazwa 'finished_products_product_code_key' pochodzi z błędu PostgreSQL.
        batch_op.drop_constraint('finished_products_product_code_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_products', schema=None) as batch_op:
        # W razie potrzeby, ta komenda przywróci starą regułę
        batch_op.create_unique_constraint('finished_products_product_code_key', ['product_code'])

    # ### end Alembic commands ###
