"""Add ActivityLog table

Revision ID: 251ddcbbf24b
Revises: 1fcbdb3a7af9
Create Date: 2025-10-03 17:12:02.878269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251ddcbbf24b'
down_revision = '1fcbdb3a7af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
