"""Add category to vacation requests

Revision ID: 60da692b8fb2
Revises: 6d017d6a4d03
Create Date: 2025-10-13 11:42:15.133861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60da692b8fb2'
down_revision = '6d017d6a4d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacation_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacation_requests', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
