"""Add team availability flag to product categories

Revision ID: 6d017d6a4d03
Revises: 04d473b83321
Create Date: 2025-10-08 20:02:57.713621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d017d6a4d03'
down_revision = '04d473b83321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_product_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_for_team', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_product_categories', schema=None) as batch_op:
        batch_op.drop_column('available_for_team')

    # ### end Alembic commands ###
