"""Add many-to-many relationship for packaging and sales log

Revision ID: 82746e2893eb
Revises: acb7e1123592
Create Date: 2025-09-29 22:49:52.094098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82746e2893eb'
down_revision = 'acb7e1123592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_packaging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finished_product_id', sa.Integer(), nullable=False),
    sa.Column('packaging_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finished_product_id'], ['finished_products.id'], ),
    sa.ForeignKeyConstraint(['packaging_id'], ['packaging.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_packaging')
    # ### end Alembic commands ###
