"""Add critical stock level to RawMaterial

Revision ID: 8647ed7f6d41
Revises: bc18f8f86e4b
Create Date: 2025-09-14 13:55:00.091203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8647ed7f6d41'
down_revision = 'bc18f8f86e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_products', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_finished_products_product_code', ['product_code'])

    with op.batch_alter_table('raw_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('critical_stock_level', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_materials', schema=None) as batch_op:
        batch_op.drop_column('critical_stock_level')

    with op.batch_alter_table('finished_products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_finished_products_product_code', type_='unique')

    # ### end Alembic commands ###
