"""Implementacja sledzenia partii w magazynie

Revision ID: 94644ee05edc
Revises: 
Create Date: 2025-09-12 09:52:08.893060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94644ee05edc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_material_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('quantity_on_hand', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_materials', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('quantity_in_stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_in_stock', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=20), nullable=False))

    op.drop_table('raw_material_batches')
    # ### end Alembic commands ###
