"""Add critical stock level to Packaging

Revision ID: a420f50dd144
Revises: 940589aeaed3
Create Date: 2025-09-16 21:57:16.382203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a420f50dd144'
down_revision = '940589aeaed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packaging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('critical_stock_level', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packaging', schema=None) as batch_op:
        batch_op.drop_column('critical_stock_level')

    # ### end Alembic commands ###
