"""Remove unique constraint from product_code

Revision ID: a654f61bc5f6
Revises: e47b1795f289
Create Date: 2025-09-15 11:51:28.915091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a654f61bc5f6'
down_revision = 'e47b1795f289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_finished_products_product_code'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_products', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_finished_products_product_code'), ['product_code'])

    # ### end Alembic commands ###
